clientAddr: http://localhost:3000

server:
  port: 8082

spring:
  application:
    name: projects

  # Configuration for the connection string to MongoDB database
  data:
    mongodb:
      # Configure database location
      host: localhost
      port: 27017
      database: aseProject

      # Configure credential
      username: aseAdmin
      password: password
      authentication-database: admin

      # Configure Database Operation,
      # allow creating index automatically from the code
      auto-index-creation: true

      #enable the usage of Spring Data Mongo Repository
      repositories:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true